### ISSUE TITLE
size  problem in TVAttFlat 

### ISSUE THREAD

**Issue by codewithFlycat** [deep-spin/TVmax#1]
`forward(self, x, x_mask, size, eval_=False):
`
hello ,i am a master who are working on VQA
i seached all the code in run.py 、exec.py and net.py
there is no descriptions about the variable ‘size’ in class TVAttFlat
i'm wonder what does the 'size' means and how should i set it?
could you tell me more about the variable ‘size’ on it's meanings and values?
thanks !!!

**Comment by erikdao** [comment]
I'm interested in this question as well. I hope the authors could provide an answer to it.

**Comment by pedrohenriqueamartins** [comment]
The 'size' variable corresponds to the size of the image grid (horizontal and vertical), since not all images have the same original size.
The code was not up to date, but I've updated it after codewithFlycat opened this issue.
